# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create a new version

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Build project
        run: |
          npm ci
          cd app/ && npm ci && cd ..
          npm run build:prod
      - name: Version
        if: !startsWith(github.event.head_commit.message, 'chore')
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github
          author_email: actions@github.com
        run: |
          git tag | xargs git tag -d
          npm run version
          git push origin --tags
      - name: Package
        if: startsWith(github.event.head_commit.message, 'chore')
        run: |
          npm run electron:build
      - name: Release
        if: startsWith(github.event.head_commit.message, 'chore')
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            CHANGELOG.md
            release/*
